using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Linq;
using System.Windows.Forms;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace LightenedDream.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightenedDream.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		static internal System.Drawing.Bitmap Action_Record {
			get {
				object obj = ResourceManager.GetObject("Action.Record", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Action1 {
			get {
				object obj = ResourceManager.GetObject("Action1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Categories {
			get {
				object obj = ResourceManager.GetObject("Categories", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Character2 {
			get {
				object obj = ResourceManager.GetObject("Character2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Dream_Final {
			get {
				object obj = ResourceManager.GetObject("Dream.Final", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Dream_Final_2 {
			get {
				object obj = ResourceManager.GetObject("Dream.Final.2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Dream_Final1 {
			get {
				object obj = ResourceManager.GetObject("Dream.Final1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Dream_Final2 {
			get {
				object obj = ResourceManager.GetObject("Dream.Final2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Dream4 {
			get {
				object obj = ResourceManager.GetObject("Dream4", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Emotions {
			get {
				object obj = ResourceManager.GetObject("Emotions", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Folder_16 {
			get {
				object obj = ResourceManager.GetObject("Folder.16", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Folder_Launch_16 {
			get {
				object obj = ResourceManager.GetObject("Folder.Launch.16", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Function_Blank {
			get {
				object obj = ResourceManager.GetObject("Function.Blank", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Function_Blank_2 {
			get {
				object obj = ResourceManager.GetObject("Function.Blank.2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Function_Play {
			get {
				object obj = ResourceManager.GetObject("Function.Play", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Function_Record {
			get {
				object obj = ResourceManager.GetObject("Function.Record", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Function_Stop {
			get {
				object obj = ResourceManager.GetObject("Function.Stop", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Graph_Export {
			get {
				object obj = ResourceManager.GetObject("Graph.Export", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Graph_Import {
			get {
				object obj = ResourceManager.GetObject("Graph.Import", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Locations {
			get {
				object obj = ResourceManager.GetObject("Locations", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Lucidity {
			get {
				object obj = ResourceManager.GetObject("Lucidity", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Lucidity2 {
			get {
				object obj = ResourceManager.GetObject("Lucidity2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap objectsdl {
			get {
				object obj = ResourceManager.GetObject("objectsdl", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap Themes {
			get {
				object obj = ResourceManager.GetObject("Themes", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
