using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace lucidcode.LightenedDream.Lucidity.My
{

	[System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"), System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase
	{

		private static MySettings defaultInstance = (MySettings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings());

		#region "My.Settings Auto-Save Functionality"
		#endregion

		public static MySettings Default {
			get {

				if (!addedHandler) {
					lock (addedHandlerLockObject) {
						if (!addedHandler) {
							MyProject.Application.Shutdown += AutoSaveSettings;
							addedHandler = true;
						}
					}
				}
				return defaultInstance;
			}
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("Verdana, 8.25pt")]
		public global::System.Drawing.Font Font {
			get { return (global::System.Drawing.Font)this["Font"]; }
			set { this["Font"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("LightSteelBlue")]
		public global::System.Drawing.Color FormBackColor {
			get { return (global::System.Drawing.Color)this["FormBackColor"]; }
			set { this["FormBackColor"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
		public global::System.Drawing.Color TitleBackColor {
			get { return (global::System.Drawing.Color)this["TitleBackColor"]; }
			set { this["TitleBackColor"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("White")]
		public global::System.Drawing.Color TitleForeColor {
			get { return (global::System.Drawing.Color)this["TitleForeColor"]; }
			set { this["TitleForeColor"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("MidnightBlue")]
		public global::System.Drawing.Color FormForeColor {
			get { return (global::System.Drawing.Color)this["FormForeColor"]; }
			set { this["FormForeColor"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("White")]
		public global::System.Drawing.Color TextBackColor {
			get { return (global::System.Drawing.Color)this["TextBackColor"]; }
			set { this["TextBackColor"] = value; }
		}
	}
}

namespace lucidcode.LightenedDream.Lucidity.My
{

	[Microsoft.VisualBasic.HideModuleNameAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	static internal class MySettingsProperty
	{

		[System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]
		static internal global::lucidcode.LightenedDream.Lucidity.My.MySettings Settings {
			get { return global::lucidcode.LightenedDream.Lucidity.My.MySettings.Default; }
		}
	}
}
